version: '{build}'
branches:
  only:
    - master
    - develop
clone_folder: c:\Users\Alexey\source\repos\
image:
  - Visual Studio 2017
configuration:
  - Release
  - Debug
platform:
  - x64
environment:
  matrix:
    - arch: Win64
  # - arch: #does not work, Release|x64 not a valid target
matrix:
  fast_finish: true

# skip unsupported combinations
init:
init:
  - set PATH=%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\MSBuild.exe;%PATH%
  - set arch=
  - if "%arch%"=="Win64" ( set arch= Win64)
  - echo %arch%
  - echo %APPVEYOR_BUILD_WORKER_IMAGE%
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
  - echo %generator%

before_build:
  - cmd: |-
      mkdir build
      cd build
      cmake --version
      cmake .. -G %generator%

build:
  project: c:\Users\Alexey\source\repos\HW1-s2-master\dz1_s2.sln
  verbosity: minimal
  parallel: true
